AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slackbot

  SAM Template for slackbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SlackBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: botcore/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        SlackBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bot
            Method: POST
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackBotApi:
    Description: "API Gateway endpoint URL for Prod stage for SlackBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bot/"
  SlackBotFunction:
    Description: "SlackBot Lambda Function ARN"
    Value: !GetAtt SlackBotFunction.Arn
  SlackBotFunctionIamRole:
    Description: "Implicit IAM Role created for SlackBot function"
    Value: !GetAtt SlackBotFunctionRole.Arn

Parameters:
  SlackToken:
    Type: String